<a href="https://colab.research.google.com/github/amgurkas/adv-programming/blob/main/week6/DiscussionPost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 1. What are the similarities and differences between pandas and numpy?
# Include some type of example with code.

# Both pandas and NumPy are libraries used for working with data, but they serve
# slightly different purposes. I often use NumPy for numeric computations and
# pandas when I need labeled, tabular data

# Similarities: vectorized operations and efficiency
# Differences: data structures, handling of mixed types, missing values

### Ex. Code:
import pandas as pd
import NumPy as np

df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Salary": [50000, 60000, 70000]
})
print(df)

arr = np.array([[25, 50000], [30, 60000], [35, 70000]])
print(arr)

# Notice that the NumPy array cannot easily store names without converting
# everything to strings



# 2. What is the ndarray in numPy?
# A NumPy ndarray, short for N-dimensional array, is a core component of NumPy.
# It efficiently stores and manipulates large, homogeneous datasets of the same
# data type. Its multi-dimensional structure is well-suited for complex data in
# scientific computing and data analysis, enabling fast and memory-efficient
# operations.
# (Source: https://www.geeksforgeeks.org/numpy/numpy-ndarray/)

# 3. Create a 1D array of numbers from 0 to 9
# Desired Output:
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# 4. Extract all odd numbers from array1
# array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# 5. Get the common items between a and  b
#input
# a = np.array([1,2,3,2,3,4,3,4,5,6])
# b = np.array([7,2,10,2,7,4,9,4,9,8])

#Desired Output:

# array([2, 4])
# 6. From array a remove all items present in array  b
#Input:

# a = np.array([1,2,3,4,5])
# b = np.array([5,6,7,8,9])

#Desired Output:

# array([1,2,3,4])
# 7. Find out if iris has any missing values.
# Input
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
# iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])